// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChannelTags     string
	Channels        string
	IPLog           string
	RoomEditorUsers string
	RoomTags        string
	Rooms           string
	ServiceInfo     string
	Tags            string
	UserConfig      string
	Users           string
}{
	ChannelTags:     "channel_tags",
	Channels:        "channels",
	IPLog:           "ip_log",
	RoomEditorUsers: "room_editor_users",
	RoomTags:        "room_tags",
	Rooms:           "rooms",
	ServiceInfo:     "service_info",
	Tags:            "tags",
	UserConfig:      "user_config",
	Users:           "users",
}
